# Generated by Django 5.1.15 on 2026-08-31 16:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('users', '0002_user_email_verified_user_phone_user_phone_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('qr', 'QR'), ('gps', 'GPS'), ('manual', 'Manual'), ('admin', 'Admin')], default='qr', max_length=16)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('review', 'Review')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='users.userdevice')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='gyms.gym')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='gyms.checkinsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'gym', 'checked_in_at'], name='checkins_user_gym_ci_idx'), models.Index(fields=['user', 'status', 'created_at'], name='checkins_user_status_cr_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='checkins_checkin_unique_user_idempotency_key')],
            },
        ),
    ]
