# Generated by Django 5.1.15 on 2026-08-31 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('qr_reuse', 'QR reuse'), ('gps_mismatch', 'GPS mismatch'), ('too_many_checkins', 'Too many check-ins'), ('impossible_travel', 'Impossible travel'), ('multiple_accounts_device', 'Multiple accounts on device'), ('suspicious_pattern', 'Suspicious pattern'), ('device_anomaly', 'Device anomaly')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_events', to='checkins.checkin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='fraud_fraud_user_id_ab4108_idx')],
            },
        ),
    ]
