# Generated by Django 5.1.15 on 2026-09-01 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudevent',
            name='event_type',
            field=models.CharField(choices=[('qr_reuse', 'QR reuse'), ('gps_mismatch', 'GPS mismatch'), ('too_many_checkins', 'Too many check-ins'), ('impossible_travel', 'Impossible travel'), ('multiple_accounts_device', 'Multiple accounts on device'), ('suspicious_pattern', 'Suspicious pattern'), ('device_anomaly', 'Device anomaly'), ('suspicious_account_creation', 'Suspicious account creation'), ('suspicious_reward_claim', 'Suspicious reward claim')], max_length=32),
        ),
        migrations.CreateModel(
            name='FraudReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reviews_resolved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fraudevent',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='fraud.fraudreview'),
        ),
        migrations.AddIndex(
            model_name='fraudreview',
            index=models.Index(fields=['user', 'status'], name='fraud_fraud_user_id_869637_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreview',
            index=models.Index(fields=['status', 'created_at'], name='fraud_fraud_status_c0ff4a_idx'),
        ),
    ]
