# Generated by Django 5.1.15 on 2026-09-06 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_user_phone_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames can only contain lowercase letters, numbers, and underscores (3-30 characters).', regex='^[a-z0-9_]{3,30}$')]),
        ),
    ]
