# Generated by Django 5.1.15 on 2026-08-31 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='rewards_pro_status_3d8b39_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=32)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='rewards.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('restock', 'Restock'), ('reserve', 'Reserve'), ('release', 'Release'), ('ship', 'Ship')], max_length=16)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='rewards.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='RewardDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('merchandise', 'Merchandise')], default='merchandise', max_length=16)),
                ('required_streak', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('terms', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_definitions', to='rewards.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('claimed', 'Claimed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='earned', max_length=16)),
                ('claim_code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('reward_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_rewards', to='rewards.rewarddefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.JSONField()),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('carrier', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('claimed', 'Claimed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='claimed', max_length=16)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='rewards.productvariant')),
                ('user_reward', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='rewards.userreward')),
            ],
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='rewards_pro_product_e8d2e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['variant', 'created_at'], name='rewards_inv_variant_d0e36e_idx'),
        ),
        migrations.AddIndex(
            model_name='rewarddefinition',
            index=models.Index(fields=['status', 'required_streak'], name='rewards_rew_status_8def9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['user', 'status'], name='rewards_use_user_id_91fc31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userreward',
            unique_together={('user', 'reward_definition')},
        ),
        migrations.AddIndex(
            model_name='rewardclaim',
            index=models.Index(fields=['status'], name='rewards_rew_status_da0e28_idx'),
        ),
    ]
