# Generated by Django 5.1.15 on 2026-09-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarddefinition',
            name='block_if_high_risk_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rewarddefinition',
            name='minimum_account_age_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewarddefinition',
            name='minimum_verified_checkins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewarddefinition',
            name='require_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rewarddefinition',
            name='require_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
