# Generated by Django 5.1.15 on 2026-09-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewarddefinition_block_if_high_risk_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardclaim',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='type',
            field=models.CharField(choices=[('restock', 'Restock'), ('reserve', 'Reserve'), ('release', 'Release'), ('ship', 'Ship'), ('adjustment', 'Adjustment')], max_length=16),
        ),
    ]
