# Generated by Django 5.1.15 on 2026-09-05 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gymstaffinvite'),
        ('rewards', '0003_rewardclaim_delivered_at_rewardclaim_shipped_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerkRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('claimed', 'Claimed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='claimed', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='rewarddefinition',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_definitions', to='gyms.gym'),
        ),
        migrations.AlterField(
            model_name='rewarddefinition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_definitions', to='rewards.product'),
        ),
        migrations.AlterField(
            model_name='rewarddefinition',
            name='reward_type',
            field=models.CharField(choices=[('merchandise', 'Merchandise'), ('perk', 'Perk')], default='merchandise', max_length=16),
        ),
        migrations.AlterField(
            model_name='rewarddefinition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='rewarddefinition',
            index=models.Index(fields=['gym', 'status'], name='rewards_rew_gym_id_5ed023_idx'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['claim_code_hash'], name='rewards_use_claim_c_30260c_idx'),
        ),
        migrations.AddField(
            model_name='perkredemption',
            name='user_reward',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perk_redemption', to='rewards.userreward'),
        ),
        migrations.AddField(
            model_name='perkredemption',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_perk_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='perkredemption',
            index=models.Index(fields=['status'], name='rewards_per_status_c272cf_idx'),
        ),
    ]
