# Generated by Django 5.1.15 on 2026-08-31 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('checkin_radius_meters', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='gyms_gym_status_855aa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='GymCheckinDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('last_rotation_at', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_devices', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='gyms.gym')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='gyms.gymcheckindevice')),
            ],
        ),
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff'), ('manager', 'Manager'), ('owner', 'Owner')], default='member', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gymcheckindevice',
            index=models.Index(fields=['gym', 'status'], name='gyms_gymche_gym_id_6b41e4_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['token_hash', 'status'], name='gyms_checki_token_h_edeb96_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['device', 'status'], name='gyms_checki_device__e128c8_idx'),
        ),
        migrations.AddIndex(
            model_name='gymmembership',
            index=models.Index(fields=['gym', 'role', 'status'], name='gyms_gymmem_gym_id_d0bb1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gymmembership',
            unique_together={('user', 'gym')},
        ),
    ]
