# Generated by Django 5.1.15 on 2026-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
    ]
