# Generated by Django 5.1.15 on 2026-09-06 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gymstaffinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='checkin_radius_meters',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
