# Generated by Django 5.1.15 on 2026-09-06 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('checkin', 'Check-in'), ('streak_milestone', 'Streak milestone'), ('badge_earned', 'Badge earned'), ('workout_completed', 'Workout completed')], max_length=32)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=32)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='social_acti_user_id_170908_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('related_object_id__isnull', False)), fields=('user', 'type', 'related_object_type', 'related_object_id'), name='uniq_activity_per_related_object')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_links', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['following'], name='social_foll_followi_3e6f69_idx'), models.Index(fields=['follower'], name='social_foll_followe_9bcca8_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='uniq_follow_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow')],
            },
        ),
    ]
