# Generated by Django 5.1.15 on 2026-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('streak_milestone', 'Streak milestone'), ('reward_unlocked', 'Reward unlocked'), ('reward_shipped', 'Reward shipped'), ('challenge', 'Challenge'), ('new_follower', 'New follower'), ('system', 'System')], max_length=32),
        ),
    ]
